
version: '3.9'
services:
  backend:
    build:
      context: ./backend
      # dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - 3333:3333
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
  frontend:
    build:
      context: ./frontend
   # dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres 
      - backend
    env_file:
      - ./frontend/.env

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
